const AvailableProducts = [
  {
    id: 1,
    code: "B1",
    type: "book",
    name: "Book1",
    description: "desc of book1",
    price: 100,
    image: "book-black.jpg",
  },
  {
    id: 2,
    code: "B1",
    type: "book",
    name: "Book1",
    description: "desc of book1",
    price: 100,
    image: "book-black.jpg",
  },
  {
    id: 3,
    code: "B2",
    type: "book",
    name: "Book2",
    description: "desc of book2",
    price: 200,
    image: "book-green.jpg",
  },
  {
    id: 4,
    code: "B3",
    type: "book",
    name: "Book3",
    description: "desc of book3",
    price: 400,
    image: "book-red.jpg",
  },
  {
    id: 5,
    code: "B4",
    type: "book",
    name: "Book4",
    description: "desc of book4",
    price: 500,
    image: "book-yellow.jpg",
  },
  {
    id: 6,
    code: "B4",
    type: "book",
    name: "Book4",
    description: "desc of book4",
    price: 500,
    image: "book-yellow.jpg",
  },
];

export default AvailableProducts;
