import React from "react";
import TopBarItem from "./TopBarItem";
import ".././styles.css";

function TopBar({ onSelect, availableWindows }) {
  return (
    <div className="navbar">
      <div className="books-div">
        {
          //navBarItems generated by cycle (those in state availableWindows in App.js)
          availableWindows.map((windows) => {
            return (
              <TopBarItem
                key={windows.name}
                className="books-btn"
                windows={windows}
                onSelect={onSelect}
              />
            );
          })
        }
      </div>

      {/* Rest is staticly generated everytime */}
      <p>My book shop</p>
      <TopBarItem
        className="cart-btn"
        windows={{
          tag: "Cart",
          name: "Cart",
          image: "/Users/jakubkachlik/applicant-test-react-master/src/cart.png",
        }}
        onSelect={onSelect}
      />
    </div>
  );
}

export default TopBar;
